version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: poppo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - poppo-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: poppo-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - poppo-network
    profiles:
      - debug

volumes:
  redis-data:
    driver: local

networks:
  poppo-network:
    driver: bridge