global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'ccsp-production'
    replica: 'prometheus-1'

# アラートルール読み込み
rule_files:
  - "rules/*.yml"

# Alertmanager設定
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'

# スクレイプ設定
scrape_configs:
  # Prometheus自身
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # CCSP Agent メトリクス
  - job_name: 'ccsp-agent'
    static_configs:
      - targets: ['host.docker.internal:9090']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # Node Exporter (システムメトリクス)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # cAdvisor (コンテナメトリクス)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: /metrics

  # Alertmanager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    scrape_interval: 30s

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: /metrics

  # CCSP Dashboard API (ヘルスチェック)
  - job_name: 'ccsp-dashboard'
    static_configs:
      - targets: ['host.docker.internal:3001']
    scrape_interval: 30s
    metrics_path: /api/ccsp/health/metrics
    scrape_timeout: 10s

  # CCSP Management API
  - job_name: 'ccsp-api'
    static_configs:
      - targets: ['host.docker.internal:3001']
    scrape_interval: 15s
    metrics_path: /api/ccsp/management/metrics
    scrape_timeout: 5s

# サービス発見（将来の拡張用）
# consul_sd_configs や kubernetes_sd_configs をここに追加可能

# ストレージ設定
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true

# リモート書き込み設定（将来的にクラウド監視システムに送信する場合）
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint"
#     basic_auth:
#       username: username
#       password: password

# リモート読み込み設定
# remote_read:
#   - url: "https://prometheus-remote-read-endpoint"