apiVersion: v1
kind: ConfigMap
metadata:
  name: poppobuilder-config
  namespace: poppobuilder
data:
  NODE_ENV: "production"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  LOG_LEVEL: "info"
  AGENT_MODE: "kubernetes"
---
apiVersion: v1
kind: Secret
metadata:
  name: poppobuilder-secrets
  namespace: poppobuilder
type: Opaque
stringData:
  GITHUB_TOKEN: "${GITHUB_TOKEN}"
  DASHBOARD_PASSWORD: "${DASHBOARD_PASSWORD}"