blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/medamap/PoppoBuilderSuite/wiki
    about: Please check our documentation first
  - name: Community Support
    url: https://github.com/medamap/PoppoBuilderSuite/discussions
    about: Ask questions and discuss with the community
  - name: Security Issue
    url: https://github.com/medamap/PoppoBuilderSuite/security/policy
    about: Please report security vulnerabilities privately