# Alertmanager設定ファイル

global:
  # Slackの場合
  # slack_api_url: 'YOUR_SLACK_WEBHOOK_URL'
  
  # SMTPの場合
  # smtp_smarthost: 'smtp.example.com:587'
  # smtp_from: 'alertmanager@example.com'
  # smtp_auth_username: 'alertmanager@example.com'
  # smtp_auth_password: 'password'

# アラートをどこに送るかのルーティング
route:
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  
  # 重要度別のルーティング
  routes:
    - match:
        severity: critical
      receiver: critical-receiver
      continue: true
    
    - match:
        severity: warning
      receiver: warning-receiver

# 受信者の設定
receivers:
  - name: 'default-receiver'
    # 現在は何も設定されていない（ログのみ）
    
  - name: 'critical-receiver'
    # クリティカルアラート用
    # slack_configs:
    #   - channel: '#alerts-critical'
    #     title: 'Critical Alert'
    #     text: '{{ range .Alerts }}{{ .Annotations.summary }}\n{{ .Annotations.description }}{{ end }}'
    
  - name: 'warning-receiver'
    # 警告アラート用
    # slack_configs:
    #   - channel: '#alerts-warning'
    #     title: 'Warning Alert'
    #     text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

# 抑制ルール（重複アラートの抑制）
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']